import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const requireFromApi = createRequire(join(repoRoot, "apps/api/package.json"));
const functionName = "community-map-api";
const stageRoot = join(repoRoot, "apps/api/.cloudbase");
const functionDir = join(stageRoot, functionName);
const deployStubRoot = join(repoRoot, "apps/api/src/deploy-stubs");

const esbuild = requireFromApi("esbuild");

rmSync(functionDir, { force: true, recursive: true });
mkdirSync(functionDir, { recursive: true });

await esbuild.build({
  entryPoints: ["apps/api/src/http-function.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "cjs",
  minify: true,
  absWorkingDir: repoRoot,
  outfile: join(functionDir, "index.cjs"),
  plugins: [
    {
      name: "cloudbase-deploy-fallback",
      setup(build) {
        build.onResolve({ filter: /^@community-map\/shared$/ }, () => ({
          path: join(repoRoot, "apps/api/src/deploy-shared.ts")
        }));
        build.onResolve(
          { filter: /^@cloudbase\/(adapter-wx_mp|ai|wx-cloud-client-sdk)$/ },
          (args) => ({
            path: join(deployStubRoot, `${args.path.replace("@cloudbase/", "")}.cjs`)
          })
        );
        build.onResolve({ filter: /^mime-db$/ }, () => ({
          path: join(deployStubRoot, "mime-db.cjs")
        }));
        build.onResolve({ filter: /^web-streams-polyfill$/ }, () => ({
          path: join(deployStubRoot, "web-streams-polyfill.cjs")
        }));
        build.onResolve(
          { filter: /^\.\/tables\/(big5-added|cp936|cp949|cp950|eucjp|shiftjis)\.json$/ },
          (args) => {
            if (!args.resolveDir.includes("iconv-lite/encodings")) {
              return null;
            }

            return {
              path: join(deployStubRoot, "empty-table.json")
            };
          }
        );
        build.onResolve({ filter: /^\.\.\/mock$/ }, (args) => {
          if (
            !args.resolveDir.endsWith("apps/api/src/providers/cloudbase")
          ) {
            return null;
          }

          return {
            path: join(
              repoRoot,
              "apps/api/src/providers/cloudbase/deploy-fallback.ts"
            )
          };
        });
        build.onResolve({ filter: /^\.\/providers$/ }, (args) => {
          if (!args.resolveDir.endsWith("apps/api/src")) {
            return null;
          }

          return {
            path: join(repoRoot, "apps/api/src/providers/deploy-index.ts")
          };
        });
      }
    }
  ]
});

writeFileSync(
  join(functionDir, "package.json"),
  `${JSON.stringify(
    {
      name: "community-map-api",
      version: "0.1.0",
      private: true,
      scripts: {
        start: "node index.cjs"
      }
    },
    null,
    2
  )}\n`
);

const bootstrap = join(functionDir, "scf_bootstrap");
writeFileSync(
  bootstrap,
  [
    "#!/bin/bash",
    "set -e",
    "export PORT=${PORT:-9000}",
    "node index.cjs",
    ""
  ].join("\n")
);
chmodSync(bootstrap, 0o755);

writeFileSync(
  join(functionDir, "README.md"),
  [
    "# community-map-api CloudBase HTTP function",
    "",
    "Generated by `pnpm --filter @community-map/api build:cloudbase-http`.",
    "",
    "Deploy with CloudBase MCP using:",
    "",
    "```text",
    `manageFunctions(action="createFunction", functionRootPath="${stageRoot}", func={name:"${functionName}", type:"HTTP", protocolType:"HTTP", runtime:"Nodejs18.15", timeout:30, envVariables:{API_PROVIDER:"cloudbase", CLOUDBASE_PROVIDER_MODE:"live", CLOUDBASE_ENV_ID:"cloud1-d7gxdk8t43bd639c0"}})`,
    "```",
    "",
    "The function starts self-contained bundled `index.cjs` through `scf_bootstrap`, listens on port 9000, and reuses the canonical Koa `createApp()` route set.",
    "No runtime dependency install step is required before upload. The deploy directory intentionally contains only runtime files so CloudBase CLI direct ZIP upload stays under the platform size limit.",
    ""
  ].join("\n")
);

console.log(`Prepared ${functionName} at ${relative(repoRoot, functionDir)}`);
